### PR TITLE
upgrade bigtable and grpc client version

### PR DESCRIPTION
**Pull request by balaji**
Using the latest grpc client for dependency resolutions.

### CODE REVIEW

**Comment by balaji** [comment]
@keithmcneill

**Comment by keithmcneill** [comment]
+1

**Comment by keithmcneill** [comment]
@balaji try merging from master and see if it fixes your build problem.  Looks like travis no longer supports oraclejdk8.  I switched to openjdk8 and master builds.

**Comment by balaji** [comment]
@keithmcneill triggered another build. I don't have write access to this repo.

**Pull request merged**
