### PR TITLE
Add awesome badge

### PR DESCRIPTION
**Pull request by zrosenbauer**

### CODE REVIEW

**Comment by zrosenbauer** [comment]
Is this project still active? This PR has been sitting for quite a while.

**Comment by zrosenbauer** [comment]
Is this project still active? This PR has been sitting for quite a while.

**Review by keithmcneill — COMMENTED** [review]
Unfortunately not really active anymore

**Review by keithmcneill — COMMENTED** [review]
The library is using a fairly old version of the bigtable client library.

**Comment by zrosenbauer** [comment]
I'll remove from the bigtable list 👍

**Pull request closed without merging**
